version: "3.7"

services:
  pg:
    image: bitnami/postgresql
    container_name: alyatest-pg
    environment:
      POSTGRES_USER: alyatest
      POSTGRES_PASSWORD: alyatest
      POSTGRES_DB: alyatest
    ports:
      - "5432:5432"

  redis:
    image: redis
    container_name: alyatest-redis
    ports:
      - "6379:6379"