version: "3.7"

services:
  pg:
    image: bitnami/postgresql
    container_name: alyatest-pg
    environment:
      POSTGRES_USER: alyatest
      POSTGRES_PASSWORD: alyatest
      POSTGRES_DB: alyatest
    ports:
      - "5432:5432"

  redis:
    image: redis
    container_name: alyatest-redis
    ports:
      - "6379:6379"

  etcd:
    image: bitnami/etcd:latest
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - etcd_data:/bitnami/etcd

volumes:
  postgres_data:
  etcd_data: